### ISSUE TITLE
CriminalIp changed IP

### ISSUE THREAD

**Issue by williamdes** [wravoc/authlog-threats#2]
https://github.com/wravoc/authlog-threats/blob/b881fabba86447258136daf873bf1f9188431806/scanners#L50

Is now `94.102.61.22` according to reverse DNS and my logs

There is way more +new reports on https://www.abuseipdb.com/check/94.102.61.22

**Comment by wravoc** [comment]
Thank you so much for this update! It seems Criminal IP AiSpera stood up a whole block. Updated to `94.102.61.0/24`.

<img width="831" alt="AiSperaNetBlock" src="https://github.com/wravoc/authlog-threats/assets/121783650/ebec9f8f-cc42-46ea-b742-cd906f655f26">

**Comment by williamdes** [comment]
Coool !
That confirms my commit, I had took the /24 since mostly 99% of the IPs are abuse
Thanks for this hint, I should check the database for abuse records more often

**Comment by williamdes** [comment]
Done in 717f46e945616f991c1ee8ae406a0b77707510c8

You did commit some weird stuff into it
