### ISSUE TITLE
Binaryedge is not up to date

### ISSUE THREAD

**Issue by williamdes** [wravoc/authlog-threats#3]
Thank you so much for hinting the API endpoint !
That said it's not up to date. But still gives me some that I missed.

https://github.com/wravoc/authlog-threats/blob/717f46e945616f991c1ee8ae406a0b77707510c8/scanners#L7052

Here is my current full list: https://github.com/datacenters-network/security/blob/main/binaryedge.txt

**Comment by wravoc** [comment]
My next repo update has a function to update all IPs programmatically in the scanner file. If I delay the update for too long I will have to manually re-update them *all*, and I'd rather not ;)

**Comment by williamdes** [comment]
Hmm okay, I am not sure to understand why you replied this :)
Could you elaborate ?

Maybe It was me commenting unclear stuff: What I wanted to say is that you list is not up to date, even if you use their IP API. The API does not give all of their IPs. So, my list is more complete ;)

**Comment by wravoc** [comment]
Well, basically, I need to do what you did with [this](https://github.com/datacenters-network/security/blob/main/make-binaryedge.sh) but in my Python script so I can stop manually copy and pasting updates. 

However, I see you got a lot of good stuff going on in your repo, well done. I will need verify it though. May I ask how you got the *extra* IP's that weren't in the "official" BinaryEdge *minions* API to help me verify?

**Comment by williamdes** [comment]
> Well, basically, I need to do what you did with [this](https://github.com/datacenters-network/security/blob/main/make-binaryedge.sh) but in my Python script so I can stop manually copy and pasting updates.

Okay, I designed a Rust binary tool to handle the DNS resolving. Because other tools cost too much in cpu time. Let me know how yours performs, or use my tool :) 
We can improve it. 
Before I was using bash with xargs and dig 
It's now 5 minutes (for stretchoid) vs 25 minutes with bash... 

> However, I see you got a lot of good stuff going on in your repo, well done. I will need verify it though. May I ask how you got the _extra_ IP's that weren't in the "official" BinaryEdge _minions_ API to help me verify?

Ha, I will try to explain my reasoning in the best way possible:
- I took all IPS (ranges/CIDRs) owned by DigitalOcean (see update-digitalocean script)
- Filtered the ones that are announced with BGP (the ones really used): see the diff file in digitalocean/
- Filtered the ones that have a reverse DNS zone
- Did a massive reverse of all their IPs (https://github.com/datacenters-network/security/blob/main/digitalocean/reverse_revisions/v-2023-07-24T02%3A08%3A07%2B02%3A00.txt) 
- Filtered the results to stretchoid/binaryedge
- From the filtered results, did some complex commands to get back the CIDRs for the IPs I found: https://github.com/datacenters-network/security/blob/main/digitalocean/extract-scanner-ips.sh 
- Here is no the list https://github.com/datacenters-network/security/blob/main/digitalocean/binaryedge_ranges.txt
- Pass it into the binary prips and you have a list of IPs to reverse 
- reverse them from time to time and see if you find new allocated IPs to your search target (that's what my robot does each 8 hour, see the workflow file) 

Does it sound okay? 

Binaryedge has a difference that's major from stretchoid, their records for the PTR names give the IP of the host, not `127.0.0.1`
That did allow me to go further in the reverse of their IPs, I tool the tool names. 
Expanded the names from 0 to 100, and copied the IPs reversed into my list. One more round of my process.
See: https://github.com/datacenters-network/security/blob/main/digitalocean/binaryedge-chunk-counts.txt 

This my interest you @stamparm @szepeviktor

**Comment by szepeviktor** [comment]
Too much time spent on [stretchoid](https://www.reddit.com/r/nostalgia/comments/97432w/tacky_stretchoid_warriors/)!

**Comment by wravoc** [comment]
Fantastic work and what I've seen so far looks legit and handled well. I just ran those lists through some networks tools and I haven't found any errors. We are in the same place on this and I'm not sure how to proceed given my License and outlook for where I'm headed with this repo.

Would you like credit in the file/project, what were you looking for?

**Comment by williamdes** [comment]
> Fantastic work and what I've seen so far looks legit and handled well. I just ran those lists through some networks tools and I haven't found any errors. We are in the same place on this and I'm not sure how to proceed given my License and outlook for where I'm headed with this repo.
> 
> Would you like credit in the file/project, what were you looking for?

I am looking for everyone to have updated lists, that's mostly my main goal. Given the effort needed to make the lists it would definitely be cool to have the original repository mentioned and my github profile. No obligations :)

What is your goal with your project?

**Comment by williamdes** [comment]
Hi,
What about binaryedge?
You included only the minions but not the results I found from the analysis
is there something wrong with the data?
